### ISSUE TITLE
재귀 호출 이슈

### ISSUE THREAD

**Issue by scm1400** [saroro1/omok#1]
isOpenThree -> checkFakeThree -> isDoubleThree -> isOpenThree -> checkFakeThree -> isDoubleThree 
계속 반복되는거같습니다.
코드를 제가 조금 수정하긴했는데 금수 체크 관련 부분은 안건드렸습니다.
제가 코드를 수정한 부분에서 비롯된걸까요?

**Comment by saroro1** [comment]
> 

혹시 어느부분을 수정하셨나요? 재귀함수 호출은 상하좌우 및 대각선 8칸을 이동하여 거짓금수가 있는가를 체크하기 위함입니다

**Comment by scm1400** [comment]
답변 주셔서 감사합니다.
코드 수정 과정에서 isOpenThree 함수에 setStone하는 부분을 지워서 발생한거 같습니다 ㅠ
무안하네요  ㅎㅎ;;;
지금은 수정해서 잘 사용하고있습니다!
ZEP이라는 메타버스 플랫폼에 만든 오목게임에 사용했습니다 ㅎㅎ
https://zep.us/play/2RdjJG
